# -*- coding: utf-8 -*-
"""MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3sKb3TsOpJppwvOff5zNTVnqZjLcnHZ
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns

print("Loading Dataset...")
mnist = fetch_openml('mnist_784', version=1, parser='auto')
X=mnist.data
y=mnist.target

X.head()

def show_digits(data,labels,n_samples=10):
  """Display Sample digits from dataset"""
  fig,axes=plt.subplots(2,5,figsize=(12,6))
  axes=axes.ravel()

  for i in range(n_samples):
    image=data[i].reshape(28,28)
    axes[i].imshow(image,cmap='gray')
    axes[i].set_title(f"label : {labels[i]}")
    axes[i].axis('off')

  plt.tight_layout()
  plt.show()

show_digits(X.values,y)

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42,stratify=y
)

print(f"\nTraining samples: {X_train.shape[0]}")
print(f"Test samples: {X_test.shape[0]}")

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
print("\nData scaled successfully!")

print("Training Logistic Regression Model : ")
model=LogisticRegression(
    max_iter=100,
    solver='saga',
    random_state=42,
    verbose=1,
    n_jobs=-1
)

model.fit(X_train,y_train)

print("Making Predictions...")
y_pred_train=model.predict(X_train_scaled)
y_pred_test=model.predict(X_test_scaled)

train_accuracy = accuracy_score(y_train, y_pred_train)
test_accuracy = accuracy_score(y_test, y_pred_test)

print(f"\nTraining Accuracy: {train_accuracy * 100:.2f}%")
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")

print("\n" + "="*60)
print("CLASSIFICATION REPORT")
print("="*60)
print(classification_report(y_test, y_pred_test))

# Step 9: Confusion Matrix Visualization
cm = confusion_matrix(y_test, y_pred_test)

plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=range(10), yticklabels=range(10))
plt.title('Confusion Matrix - MNIST Digit Classification')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()


# Step 10: Prediction on New Samples
def predict_digit(model, scaler, image_index):
    """Single image ka prediction with visualization"""
    sample = X_test.iloc[image_index].values.reshape(1, -1)
    sample_scaled = scaler.transform(sample)

    prediction = model.predict(sample_scaled)[0]
    probabilities = model.predict_proba(sample_scaled)[0]

    # Visualization
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    # Image display
    ax1.imshow(X_test.iloc[image_index].values.reshape(28, 28), cmap='gray')
    ax1.set_title(f'True: {y_test.iloc[image_index]}, Predicted: {prediction}')
    ax1.axis('off')

    # Probability distribution
    ax2.bar(range(10), probabilities)
    ax2.set_xlabel('Digit')
    ax2.set_ylabel('Probability')
    ax2.set_title('Prediction Probabilities')
    ax2.set_xticks(range(10))

    plt.tight_layout()
    plt.show()

    return prediction, probabilities

# Test karte hain 5 random samples par
print("\n" + "="*60)
print("SAMPLE PREDICTIONS")
print("="*60)
np.random.seed(42)
test_indices = np.random.choice(len(X_test), 5, replace=False)

for idx in test_indices:
    pred, probs = predict_digit(model, scaler, idx)
    print(f"\nSample {idx}:")
    print(f"  True Label: {y_test.iloc[idx]}")
    print(f"  Predicted: {pred}")
    print(f"  Confidence: {probs[int(pred)]*100:.2f}%") # Changed pred to int(pred) for indexing

# Step 11: Error Analysis
errors = y_test != y_pred_test
error_indices = np.where(errors)[0]

print(f"\n\nTotal Errors: {len(error_indices)} out of {len(y_test)}")
print(f"Error Rate: {len(error_indices)/len(y_test)*100:.2f}%")

# Misclassified images dekhna
if len(error_indices) > 0:
    fig, axes = plt.subplots(2, 5, figsize=(12, 6))
    axes = axes.ravel()

    for i, idx in enumerate(error_indices[:10]):
        image = X_test.iloc[idx].values.reshape(28, 28)
        axes[i].imshow(image, cmap='gray')
        axes[i].set_title(f'True: {y_test.iloc[idx]}, Pred: {y_pred_test[idx]}')
        axes[i].axis('off')

    plt.suptitle('Misclassified Digits', fontsize=14)
    plt.show()
    print("Misclassified examples saved!")

print("\n" + "="*60)
print("ANALYSIS COMPLETE!")
print("="*60)